---
testbed_id: "${USER}-mysticeti"
cloud_provider: aws
token_file: "/Users/${USER}/.aws/credentials"
ssh_private_key_file: "/Users/${USER}/.ssh/aws"
regions:
  - us-west-1
specs: m5d.8xlarge
repository:
  url: https://github.com/asonnino/mysticeti.git
  commit: main
